MODEL:
  DEVICE: "cuda"
  DEVICE_ID: 0
  NAME: "ViT-B/16"
  PRETRAIN_PATH: ""
  STRIDE_SIZE: [16, 16]
  SIE_CAMERA: False
  SIE_VIEW: False
  SIE_COE: 3.0
  MASK_PROB: 0.5
  USE_ATTN_MASK: True
  ATTN_MASK_RATIO: 0.5
  CAA_GAMMA: 0.5
  CAA_LOSS_WEIGHT: 0.0
  ITC_LOSS_WEIGHT: 0.0
  CAA_T: 0.07

DATA:
  ROOT: "/home/jin/code/text/data/Data/ReIDData"
  DATASET: "last"
  IMG_HEIGHT: 256
  IMG_WIDTH: 128
  BATCH_SIZE: 160
  NUM_WORKERS: 8
  NUM_INSTANCES: 4
  SAMPLER: "softmax_triplet"
  PIN_MEMORY: True
  AUX_INFO: False
  RANDOM_NOISE: False
  RANDOM_PROP: 0.05

INPUT:
  SIZE_TRAIN: [256, 128]

AUG:
  RC_PROB: 0.5
  RE_PROB: 0.5
  RF_PROB: 0.5

TRAIN:
  START_EPOCH: 1

TEST:
  WEIGHT: ""
  FEAT_NORM: "yes"
  TYPE: "image_only"
  NECK_FEAT: "after"
  CROP: True

SOLVER:
  OPTIMIZER_NAME: "Adam"
  EPOCHS: 120
  BASE_LR: 1e-3
  WARMUP_LR: 1e-4
  LARGE_FC_LR: False
  BIAS_LR_FACTOR: 1
  SEED: 1234
  MOMENTUM: 0.9
  MARGIN: 0.3
  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  GAMMA: 0.1
  STEPS: [40, 60]
  WARMUP_FACTOR: 0.01
  WARMUP_EPOCHS: 10
  PRINT_FREQ: 20
  AMP_ENABLE: True
  WARMUP_METHOD: "linear"
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 100
  EVAL_PERIOD: 5

OUTPUT_DIR: "./logs/vit16_last"

TEST:
  RERANKING: True
